apiVersion: v1
kind: Service
metadata:
 name: sts-redis-cluster-headless
spec:
 clusterIP: None
 selector:
  app: redis-cluster
 ports:
  - port: 80
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: redis-cluster
 labels:
  app: redis-cluster
spec:
 serviceName: "sts-redis-cluster-headless"
 replicas: 6
 template:
  metadata:
   labels:
    app: redis-cluster
  spec:
   containers:
    - name: redis-cluster
      image: tiroshanm/kubernetes-redis-cluster:latest
      imagePullPolicy: Always
      ports:
       - containerPort: 6379
         name: client
       - containerPort: 16379 # cluster bus
         name: gossip
      command: ["/usr/local/bin/redis-server"]
      args: ["/redis-conf/redis.conf"]
      readinessProbe:
       exec:
        command:
         - sh
         - -c
         - "redis-cli -h $(hostname) ping"
       initialDelaySeconds: 15
       timeoutSeconds: 5
      livenessProbe:
       exec:
        command:
         - sh
         - -c
         - "redis-cli -h $(hostname) ping"
       initialDelaySeconds: 20
       periodSeconds: 3
      volumeMounts:
       - name: data
         mountPath: /data
         readOnly: false
 volumeClaimTemplates:
  - metadata:
     name: data
     labels:
      name: redis-cluster
    spec:
     storageClassName: manual
     accessModes:
      - ReadWriteOnce
     resources:
      requests:
       storage: 100Mi
